name: milimetric
favicon: null
layout_spectrum: 0.4734815002884716
typography_spectrum: 0.9901743882801384
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5694457893259823
  lightness: 0.7034314717166126
  saturation: 0.9383835615590215
  rhythmicContrast: 0.026585882296785712
purpose: []
